# @package _group_
_target_: satflow.data.datamodules.MaskFlowDataModule

batch_size: 6
data_dir: ${data_dir} # data_dir is specified in config.yaml
shuffle: 0
sources:
  train: "satflow-flow-144-tiled-{00001..00105}.tar"
  val: "satflow-flow-144-tiled-{00106..00129}.tar"
  test: "satflow-flow-144-tiled-{00130..00149}.tar"
num_workers: 16
pin_memory: True
config:
  visualize: False
  num_timesteps: 5
  skip_timesteps: 1
  forecast_times: 5
  output_shape: 128
  target_type: "cloudmask"
  num_crops: 10
  use_topo: True
  use_latlon: False
  use_time: False
  time_aux: False
  use_mask: True
  use_image: False
  add_pixel_coords: True
  time_as_channels: False
  bands: ["IR016"]
  transforms: {}
